//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class adresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adresses()
        {
            this.membres = new HashSet<membres>();
        }
    
        [Key]
        public int idAdresse { get; set; }

        [Required]
        public string rue { get; set; }

        [Required]
        public string noCivique { get; set; }

        [Required]
        public string ville { get; set; }

        [Required]
        public string province { get; set; }

        [Required]
        public string codePostal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membres> membres { get; set; }
    }
}
