//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDonneesBiblioEntities : DbContext
    {
        public BaseDonneesBiblioEntities()
            : base("name=BaseDonneesBiblioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresses> adresses { get; set; }
        public virtual DbSet<livres> livres { get; set; }
        public virtual DbSet<membres> membres { get; set; }
        public virtual DbSet<prets> prets { get; set; }
    }
}
